insert into options (value, label, type) values ('PZS', 'Panonske zaslanjene stepe', 'type');
-- insert into options (value, label, type) values ('SPKP', 'Suvi peskoviti krečnjački pašnjaci', 'type');
-- insert into options (value, label, type) values ('PSPL', 'Panonski stepski pašnjaci na lesu', 'type');
-- insert into options (value, label, type) values ('SLVTKSK', 'Sekundarne livade sa visokom travom koja se kosi', 'type');
-- insert into options (value, label, type) values ('LS', 'Listopadne šume', 'type');
-- insert into options (value, label, type) values ('CS', 'Četinarske šume', 'type');
-- insert into options (value, label, type) values ('SLZ', 'Suve livade sa žbunjem', 'type');
-- insert into options (value, label, type) values ('PP', 'Poljoprivredna zemljišta', 'type');
-- insert into options (value, label, type) values ('PZ', 'Planinski pašnjaci', 'type');
-- insert into options (value, label, type) values ('BMS', 'Barska i močvarna staništa', 'type');
--
-- insert into options (value, label, type) values ('NoElevation', '0-200mv', 'elevation');
-- insert into options (value, label, type) values ('ExtraSmall', '200-600mv', 'elevation');
-- insert into options (value, label, type) values ('Small', '600-800mv', 'elevation');
-- insert into options (value, label, type) values ('Medium', '800-1200mv', 'elevation');
-- insert into options (value, label, type) values ('Large', '1200-2000mv', 'elevation');
-- insert into options (value, label, type) values ('ExtraLarge', '2100-2600mv', 'elevation');
--
-- insert into options (value, label, type) values ('NoExposition', 'Ravno područje', 'exposition');
-- insert into options (value, label, type) values ('North', 'Sever', 'exposition');
-- insert into options (value, label, type) values ('NorthWest', 'Severo-zapad', 'exposition');
-- insert into options (value, label, type) values ('NorthEast', 'Severo-istok', 'exposition');
-- insert into options (value, label, type) values ('East', 'Istok', 'exposition');
-- insert into options (value, label, type) values ('West', 'Zapad', 'exposition');
-- insert into options (value, label, type) values ('South', 'Jug', 'exposition');
-- insert into options (value, label, type) values ('SouthEast', 'Jugo-istok', 'exposition');
-- insert into options (value, label, type) values ('SouthWest', 'Jugo-zapad', 'exposition');
--
-- insert into options (value, label, type) values ('ExtraCold', '5-10C', 'mjt');
-- insert into options (value, label, type) values ('VeryCold', '10-15C', 'mjt');
-- insert into options (value, label, type) values ('Cold', '15-20C', 'mjt');
-- insert into options (value, label, type) values ('Medium', '20-25C', 'mjt');
-- insert into options (value, label, type) values ('Hot', '25-30C', 'mjt');
-- insert into options (value, label, type) values ('VeryHot', '30-35C', 'mjt');
--
--
