package drools.possibleOptionsRules;
import com.sbnz.tekunicebackend.model.enums.*
import com.sbnz.tekunicebackend.model.NaturalFactorOptions


rule "Mjt options"
    when
        $h: NaturalFactorOptions( type == Type.PZS, mjtOptions == "")
    then
        $h.addMjtOptions("21-25C");
        $h.addMjtOptions("26-30C");
        $h.addMjtOptions("31-35C");
        update($h);
end

rule "Elevation options"
    when
        $h: NaturalFactorOptions( type == Type.PZS, elevationOptions == "", mjtOptions!="" )
    then
        $h.addElevationOptions("0-200mvn");
        $h.addElevationOptions("200-600mvn");
        update($h);
end

rule "Slope options"
    when
        $h: NaturalFactorOptions( type != Type.NoType, elevationOptions != "", containsElevationOption("0-200mvn") )
    then
        $h.addSlopeOptions("NoSlope");
        update($h);
end
