package sbnz.integracija;

import sbnz.integracija.example.facts.AnthropologicalFactors
import sbnz.integracija.example.facts.Habitat
import sbnz.integracija.example.facts.enums.*

dialect  "mvel"

rule "prevelik-nagib-rule"
    when
        $h : Habitat(label == Label.NO_LABEL, naturalFactors.slope == Slope.Great)
    then
        modify($h){setLabel(Label.INAPPROPRIATE)}
end

rule "cesto-plavljenje-rule"
    when
        $h : Habitat(label == Label.NO_LABEL, naturalFactors.flooding == Flooding.Often)
    then
        modify($h){setLabel(Label.INAPPROPRIATE)}
end

rule "srednji-nagib-nema-plavljenja-rule"
    when
        $h : Habitat(label == Label.NO_LABEL, naturalFactors.flooding == Flooding.None, naturalFactors.slope == Slope.Medium)
    then
        modify($h){setLabel(Label.INAPPROPRIATE)}
end

rule "mali-nagib-povremeno-plavljneje-rule"
    when
        $h : Habitat(label == Label.NO_LABEL, naturalFactors.flooding == Flooding.Sometimes, naturalFactors.slope == Slope.NoSlope)
    then
        modify($h){setLabel(Label.INAPPROPRIATE)}
end

rule "puno-zbunja-rule"
    when
        $h : Habitat($id : id, label == Label.NO_LABEL)
        $af : AnthropologicalFactors (habitat.id == $id, shrubbery.level > 5)
    then
        modify($h){setLabel(Label.INAPPROPRIATE)}
end
