package sbnz.integracija;

import sbnz.integracija.example.facts.Option
import sbnz.integracija.example.dto.RecommendationDTO

dialect  "mvel"

query doesHaveRecommendations (String x, String y)
    Option(x, y; )
    or
    ( Option(z, y; ) and doesHaveRecommendations( x, z; ) )
end

//rule "test-option-rule"
//no-loop
//    when
//        $o : Option()
//        $r : RecommendationDTO (successRate == 0)
//        not doesHaveRecommendations("0", "Veoma povoljna situacija."; )
//    then
//        modify($r){setSuccessRate(-1)}
//end

rule "best-success-rate"
no-loop
    when
        $r : RecommendationDTO (successRate == 0)
    then
        modify($r){setSuccessRate(0.9)}
        modify($r){setSuccessMessage("Ne postoje akcije koje je neophodno preduzeti.")}
end

rule "high-success-rate"
no-loop
    when
        $r : RecommendationDTO (successRate == -1, $options: recommendations)
           Number(intValue <= 40) from accumulate (
                        Option (
                            $val: Integer.valueOf(value)
                        ) from $options,
                         sum($val)
                        )
    then
        modify($r){setSuccessRate(0.8)}
        modify($r){setSuccessMessage("Ukoliko se budu ispoštovale preporučene akcije, ukoliko ih ima, šanse za uspeh su veoma velike.")}
end

rule "medium-success-rate"
no-loop
    when
        $r : RecommendationDTO (successRate == -1, $options: recommendations)
           Number(intValue <= 60, intValue >= 40) from accumulate (
                        Option (
                            $val: Integer.valueOf(value)
                        ) from $options,
                         sum($val)
                        )
    then
        modify($r){setSuccessRate(0.5)}
        modify($r){setSuccessMessage("Ukoliko se budu ispoštovale preporučene akcije šanse za uspeh su osrednje.")}

end

rule "low-success-rate"
no-loop
    when
        $r : RecommendationDTO (successRate == -1, $options: recommendations)
           Number(intValue >= 60) from accumulate (
                        Option (
                            $val: Integer.valueOf(value)
                        ) from $options,
                         sum($val)
                        )
    then
        modify($r){setSuccessRate(0.2)}
        modify($r){setSuccessMessage("Stanište verovatno nije najbolja opcija, uzimajući  u obzir da ima dosta akcija koje treba preduzeti.")}
end